# Warehouse Activity Data Preprocessing Pipeline

**Purpose:** Clean and prepare warehouse activity logs for predictive modeling

**Input:**
- Activity logs (timestamped task completions)
- Location data (aisle/bay/level)
- Product data (weight/dimensions)
- Distance matrices (precomputed travel distances)

**Output:**
- Cleaned activity dataframe with time deltas and travel distances
- Exported to parquet for modeling

**Key Transformations:**
1. Remove assignment start events (non-productive time)
2. Calculate time between consecutive tasks per worker
3. Remove outlier gaps (breaks/errors) using 98th percentile
4. Join location/product attributes
5. Calculate travel distance between tasks

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

# Define workspace and warehouse parameters
warehouse_name = "OF"
base = "~/Lucas_Systems_Capstone_Project"

# Define data file paths and schema for loading
tables = {
    f"{warehouse_name}_Activity": f"{base}/data/database_backups_csv/{warehouse_name}/{warehouse_name}_Activity.csv",
    f"{warehouse_name}_Locations": f"{base}/data/database_backups_csv/{warehouse_name}/{warehouse_name}_Locations.csv",
    f"{warehouse_name}_Products": f"{base}/data/database_backups_csv/{warehouse_name}/{warehouse_name}_Products.csv",
}

column_names = {
    f"{warehouse_name}_Activity": ["ActivityCode","UserID","WorkCode","AssignmentID","ProductID","Quantity","Timestamp","LocationID"],
    f"{warehouse_name}_Locations": ["LocationID","Aisle","Bay","Level","Slot"],
    f"{warehouse_name}_Products": ["ProductID","ProductCode","UnitOfMeasure","Weight","Cube","Length","Width","Height"],
}

# Load tables into dictionary
dfs = {}
# for name, fp in tables.items():
#     dfs[name] = pd.read_csv(fp, header=0, names=column_names[name])

# Run this if there are no column names
for name, fp in tables.items():
   dfs[name] = pd.read_csv(fp, header=None, names=column_names[name])

# Load distance matrix
path = f"{base}/data/distance_matrices/distance_matrix_{warehouse_name}.csv"
Distance = pd.read_csv(path, index_col=0)
for c in Distance.columns:
    Distance[c] = pd.to_numeric(Distance[c], errors="coerce")

In [2]:
# Display initial data summary and schema statistics
print("=" * 80)
for t in [f"{warehouse_name}_Activity", 
          f"{warehouse_name}_Locations", 
          f"{warehouse_name}_Products"]:

    print(f"Table: {t}")

    df = dfs[t]
    print(f"Dimensions: ({df.shape[0]} rows, {df.shape[1]} columns)\n")

    display(df.head(3))

    # Calculate data types and missing values
    schema_df = pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "n_missing": df.isna().sum(),
        "n_unique": df.nunique(dropna=True),
    })

    # Add numerical metrics
    num_df = df.select_dtypes(include="number")
    schema_df["min"] = num_df.min()
    schema_df["max"] = num_df.max()
    schema_df["mean"] = num_df.mean()

    display(schema_df)
    print("=" * 80)
    print("\n")

================================================================================
Table: OF_Activity
Dimensions: (127407 rows, 8 columns)

,ActivityCode,UserID,WorkCode,AssignmentID,ProductID,Quantity,Timestamp,LocationID
0,PickPut,925,20,8202090,28572.0,1.0,2025-11-10 09:21:10.613,193775.0
1,PickPut,925,20,8202091,28572.0,1.0,2025-11-10 09:21:23.520,193775.0
2,PickPut,925,20,8202092,28572.0,1.0,2025-11-10 09:21:50.800,193775.0

                dtype  n_missing  n_unique        min        max          mean
ActivityCode      str          0         2        NaN        NaN           NaN
UserID          int64          0        66       80.0     1012.0  8.936643e+02
WorkCode        int64          0         3       10.0       30.0  2.566586e+01
AssignmentID    int64          0     72319  7786482.0  8355057.0  8.146116e+06
ProductID     float64        599      9543        7.0    65494.0  2.935798e+04
Quantity      float64        599       221        1.0     2400.0  8.888177e+00
Timestamp         str          0    126979        NaN        NaN           NaN
LocationID    float64        599     10237        1.0  8294777.0  1.538827e+06

================================================================================


Table: OF_Locations
Dimensions: (44771 rows, 5 columns)

   LocationID       Aisle   Bay  Level  Slot
0           1          26  20.0    3.0   2.0
1           2          26  44.0    2.0   1.0
2           3  MANUAL PCK   NaN    NaN   NaN

              dtype  n_missing  n_unique  min        max           mean
LocationID    int64          0     44771  1.0  8294777.0  962965.682652
Aisle           str          0        71  NaN        NaN            NaN
Bay         float64          1        74  0.0      134.0      25.859482
Level       float64          1        12  1.0       45.0       3.713178
Slot        float64          2        13  1.0       67.0       3.044718

================================================================================


Table: OF_Products
Dimensions: (44771 rows, 8 columns)

   ProductID ProductCode  UnitOfMeasure  Weight  Cube  Length  Width  Height
0          1          26           20.0     3.0   2.0     NaN    NaN     NaN
1          2          26           44.0     2.0   1.0     NaN    NaN     NaN
2          3  MANUAL PCK            NaN     NaN   NaN     NaN    NaN     NaN

                 dtype  n_missing  n_unique  min        max           mean
ProductID        int64          0     44771  1.0  8294777.0  962965.682652
ProductCode        str          0        71  NaN        NaN            NaN
UnitOfMeasure  float64          1        74  0.0      134.0      25.859482
Weight         float64          1        12  1.0       45.0       3.713178
Cube           float64          2        13  1.0       67.0       3.044718
Length         float64      44771         0  NaN        NaN            NaN
Width          float64      44771         0  NaN        NaN            NaN
Height         float64      44771         0  NaN        NaN            NaN

================================================================================

In [3]:
display(Distance.head())

# Convert Distance matrix to a long-format DataFrame for easier lookups
dist_long = (
    # Distance.stack(dropna=False)
    Distance.stack()
    .rename("distance")
    .reset_index()
    .rename(columns={"level_0": "FromLoc", "level_1": "ToLoc"})
)

display(dist_long.head())

,19|60|||,19|58|||,19|56|||,19|54|||,19|52|||,19|50|||,19|48|||,19|46|||,19|44|||,19|42|||,...,|Start 06,|Start 07,|Start 08,|Start 09,|Start 10,|Start 11,|Start 12,|Start 13,|Start 14,|Start L2
19|60|||,0,7,15,22,30,37,45,53,60,68,...,804,773,785,704,716,744,732,813,801,822
19|58|||,478,0,7,15,22,30,38,45,53,60,...,796,765,777,696,708,736,724,805,793,814
19|56|||,471,478,0,7,15,22,30,38,45,53,...,789,758,770,689,701,728,717,797,786,806
19|54|||,463,471,478,0,7,15,22,30,37,45,...,781,750,762,681,693,721,709,790,778,799
19|52|||,456,463,471,478,0,7,15,22,30,37,...,773,742,754,673,685,713,701,782,770,791

    FromLoc     ToLoc  distance
0  19|60|||  19|60|||         0
1  19|60|||  19|58|||         7
2  19|60|||  19|56|||        15
3  19|60|||  19|54|||        22
4  19|60|||  19|52|||        30

In [4]:
activity_key = f"{warehouse_name}_Activity"
locations_key = f"{warehouse_name}_Locations"
products_key = f"{warehouse_name}_Products"

# Clean activity data for merging
dfs[activity_key]["ProductID"] = pd.to_numeric(dfs[activity_key]["ProductID"], errors="coerce").astype("Int64")
dfs[activity_key]["Quantity"]  = pd.to_numeric(dfs[activity_key]["Quantity"], errors="coerce").astype("Int64")
dfs[activity_key]["LocationID"] = pd.to_numeric(dfs[activity_key]["LocationID"], errors="coerce").astype("Int64")
dfs[activity_key]["Timestamp"] = pd.to_datetime(dfs[activity_key]["Timestamp"], errors="coerce")
dfs[activity_key]["UserID"] = dfs[activity_key]["UserID"].astype(str)
dfs[activity_key]["WorkCode"] = dfs[activity_key]["WorkCode"].astype(str)
dfs[activity_key]["AssignmentID"] = dfs[activity_key]["AssignmentID"].astype(str)
dfs[activity_key] = dfs[activity_key].dropna(subset=["Timestamp"]).copy()

# Clean location data for merging
dfs[locations_key]["LocationID"] = pd.to_numeric(dfs[locations_key]["LocationID"], errors="coerce").astype("Int64")
for col in ["Bay", "Level", "Slot"]:
    dfs[locations_key][col] = pd.to_numeric(dfs[locations_key][col], errors="coerce").astype("Int64")

# Clean product data for merging
dfs[products_key]["ProductID"] = pd.to_numeric(dfs[products_key]["ProductID"], errors="coerce").astype("Int64")
dfs[products_key] = dfs[products_key][["ProductID", "ProductCode", "UnitOfMeasure", "Weight", "Cube"]]

Activity = dfs[activity_key]
Locations = dfs[locations_key]
Products = dfs[products_key]

In [5]:
df_work = Activity.copy()
df_work = df_work.sort_values(["UserID", "Timestamp"]).reset_index(drop=True)

# Calculate time deltas between consecutive user tasks to identify task completion time
g = df_work.groupby("UserID", sort=False)
df_work["Prev_Timestamp"] = g["Timestamp"].shift(1)
df_work["Prev_LocationID"] = g["LocationID"].shift(1)

df_work["Time_Delta_sec"] = (
    df_work["Timestamp"] - df_work["Prev_Timestamp"]
).dt.total_seconds()

# Filter out gaps exceeding the 98th percentile (interpreting as breaks, chats, etc.)
threshold = df_work["Time_Delta_sec"].quantile(0.98)
print(f"98th Percentile Threshold: {threshold:.2f} seconds ({(threshold/60):.2f} minutes)")
df_work.loc[df_work["Time_Delta_sec"] > threshold, "Time_Delta_sec"] = np.nan
print(f"Number of rows with Time Deltas: {len(df_work[df_work['Time_Delta_sec'].notnull()])}")

Activity_prepped = df_work
display(Activity_prepped.head())

98th Percentile Threshold: 563.88 seconds (9.40 minutes)
Number of rows with Time Deltas: 124794

,ActivityCode,UserID,WorkCode,AssignmentID,ProductID,Quantity,Timestamp,LocationID,Prev_Timestamp,Prev_LocationID,Time_Delta_sec
0,PickPut,1001,20,8202054,4745,1,2025-11-10 10:16:39.143,73575,NaT,<NA>,NaN
1,PickPut,1001,20,8202055,4745,1,2025-11-10 10:17:03.137,73575,2025-11-10 10:16:39.143,73575,23.994
2,PickPut,1001,20,8202056,4745,1,2025-11-10 10:17:24.510,73575,2025-11-10 10:17:03.137,73575,21.373
3,PickPut,1001,20,8202057,4745,1,2025-11-10 10:17:43.713,73575,2025-11-10 10:17:24.510,73575,19.203
4,PickPut,1001,20,8202058,63429,1,2025-11-10 10:19:58.057,1998192,2025-11-10 10:17:43.713,73575,134.344

In [6]:
# Join Activity data with Product and Location features
df_joined = Activity_prepped.merge(Products, on="ProductID", how="left")
df_joined = df_joined.merge(Locations, on="LocationID", how="left")

df_joined = df_joined.merge(
    Locations[["LocationID","Aisle","Bay","Level","Slot"]].rename(columns={
        "LocationID": "Prev_LocationID",
        "Aisle": "Prev_Aisle",
        "Bay": "Prev_Bay",
        "Level": "Prev_Level",
        "Slot": "Prev_Slot",
    }),
    on="Prev_LocationID",
    how="left"
)

display(df_joined.head())

,ActivityCode,UserID,WorkCode,AssignmentID,ProductID,Quantity,Timestamp,LocationID,Prev_Timestamp,Prev_LocationID,...,Weight,Cube,Aisle,Bay,Level,Slot,Prev_Aisle,Prev_Bay,Prev_Level,Prev_Slot
0,PickPut,1001,20,8202054,4745,1,2025-11-10 10:16:39.143,73575,NaT,<NA>,...,NaN,NaN,20,6,5,2,NaN,<NA>,<NA>,<NA>
1,PickPut,1001,20,8202055,4745,1,2025-11-10 10:17:03.137,73575,2025-11-10 10:16:39.143,73575,...,NaN,NaN,20,6,5,2,20,6,5,2
2,PickPut,1001,20,8202056,4745,1,2025-11-10 10:17:24.510,73575,2025-11-10 10:17:03.137,73575,...,NaN,NaN,20,6,5,2,20,6,5,2
3,PickPut,1001,20,8202057,4745,1,2025-11-10 10:17:43.713,73575,2025-11-10 10:17:24.510,73575,...,NaN,NaN,20,6,5,2,20,6,5,2
4,PickPut,1001,20,8202058,63429,1,2025-11-10 10:19:58.057,1998192,2025-11-10 10:17:43.713,73575,...,NaN,NaN,20,46,5,2,20,6,5,2

In [7]:
df_detailed = df_joined.copy()

df_detailed["Aisle2"] = pd.to_numeric(df_detailed["Aisle"], errors="coerce").astype("Int64").astype(str).str.zfill(2)
df_detailed["Bay2"] = pd.to_numeric(df_detailed["Bay"], errors="coerce").astype("Int64").astype(str).str.zfill(2)
df_detailed["Prev_Aisle2"] = pd.to_numeric(df_detailed["Prev_Aisle"], errors="coerce").astype("Int64").astype(str).str.zfill(2)
df_detailed["Prev_Bay2"] = pd.to_numeric(df_detailed["Prev_Bay"], errors="coerce").astype("Int64").astype(str).str.zfill(2)

# Create location keys and map travel distances
df_detailed["LocKey"] = df_detailed["Aisle2"] + "|" + df_detailed["Bay2"] + "|||"
df_detailed["PrevLocKey"] = df_detailed["Prev_Aisle2"] + "|" + df_detailed["Prev_Bay2"] + "|||"

# Calculate travel distances using the distance matrix (long format)
df_detailed = df_detailed.merge(
    dist_long,
    left_on=["LocKey", "PrevLocKey"],
    right_on=["FromLoc", "ToLoc"],
    how="left"
).rename(columns={"distance": "Travel_Distance"}).drop(columns=["FromLoc", "ToLoc"])

display(df_detailed.head())

,ActivityCode,UserID,WorkCode,AssignmentID,ProductID,Quantity,Timestamp,LocationID,Prev_Timestamp,Prev_LocationID,...,Prev_Bay,Prev_Level,Prev_Slot,Aisle2,Bay2,Prev_Aisle2,Prev_Bay2,LocKey,PrevLocKey,Travel_Distance
0,PickPut,1001,20,8202054,4745,1,2025-11-10 10:16:39.143,73575,NaT,<NA>,...,<NA>,<NA>,<NA>,20,06,NaN,NaN,20|06|||,NaN,NaN
1,PickPut,1001,20,8202055,4745,1,2025-11-10 10:17:03.137,73575,2025-11-10 10:16:39.143,73575,...,6,5,2,20,06,20,06,20|06|||,20|06|||,0.0
2,PickPut,1001,20,8202056,4745,1,2025-11-10 10:17:24.510,73575,2025-11-10 10:17:03.137,73575,...,6,5,2,20,06,20,06,20|06|||,20|06|||,0.0
3,PickPut,1001,20,8202057,4745,1,2025-11-10 10:17:43.713,73575,2025-11-10 10:17:24.510,73575,...,6,5,2,20,06,20,06,20|06|||,20|06|||,0.0
4,PickPut,1001,20,8202058,63429,1,2025-11-10 10:19:58.057,1998192,2025-11-10 10:17:43.713,73575,...,6,5,2,20,46,20,06,20|46|||,20|06|||,322.0

In [8]:
# Export processed files
output_dir = Path("~/Lucas_Systems_Capstone_Project/data/processed")
output_dir.mkdir(parents=True, exist_ok=True)

df_detailed.to_parquet(output_dir / f"{warehouse_name.lower()}_detailed_withAO.parquet", index=False)
Activity_prepped.to_parquet(output_dir / f"{warehouse_name.lower()}_activity_prepped_withAO.parquet", index=False)
df_joined.to_parquet(output_dir / f"{warehouse_name.lower()}_joined_withAO.parquet", index=False)

print(f"Successfully exported all {warehouse_name} files to {output_dir}")

Successfully exported all OF files to ~/Lucas_Systems_Capstone_Project/data/processed

In [9]:
# Drop assignment-opening noise to refine dataset to pure pick task cycles
open_indices = df_detailed[df_detailed["ActivityCode"] == "AssignmentOpen"].index
first_activity_indices = open_indices + 1
to_drop = open_indices.union(first_activity_indices).intersection(df_detailed.index)

# Create the final cleaned dataset
Detailed_Data = df_detailed.drop(to_drop).reset_index(drop=True)

In [10]:
# Export processed files
Detailed_Data.to_parquet(output_dir / f"{warehouse_name.lower()}_detailed.parquet", index=False)
Activity_prepped.to_parquet(output_dir / f"{warehouse_name.lower()}_activity_prepped.parquet", index=False)
df_joined.to_parquet(output_dir / f"{warehouse_name.lower()}_joined.parquet", index=False)

print(f"Successfully exported all {warehouse_name} files to {output_dir}")

Successfully exported all OF files to ~/Lucas_Systems_Capstone_Project/data/processed